app:
  name: "web_app"
  mode: "dev"
  port:  8080
  version: "1.0.1"
  machine_id: 1
  start_time: "2020-07-01"
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "192.168.1.9"
  user: "admin"
  dbname: "reddit"
  password: "123456"
  port: 3306
  id_conns: 50
  open_connect: 100
redis:
  host: "192.168.1.9"
  port: 6379
  user: a
  dbname: 0
  password: ""
  pool_size: 100
